apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  namespace: diploma
  labels:
    app: guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      imagePullSecrets:
        - name: yc-registry
      containers:
        - name: guestbook
          image: cr.yandex/<registry_id>/guestbook:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: APP_VERSION
              value: "dev"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: guestbook-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: guestbook-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: guestbook-secret
                  key: DB_PASSWORD
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /db-check
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
